---
title: "Regresinė Analizė"
author: "Vainius Gataveckas, Matas Gaulia, Dovydas Martinkus"
output:
  html_document: default
---


```{r, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)
```

```{r}
library(tidyverse)
library(car)
library(janitor)
x <- read_csv("life.csv") %>% clean_names()
```

### Tikslas: prognozuoti vidutine gyvenimo trukme salyje pagal tam tikrus sveikatos rodiklius


```{r}
set.seed(100)
transform_1<- function(x) {
  x %>%
  mutate(gdp_per_capita = gdp / population) %>%
  group_by(country) %>%
  fill(everything(), .direction = "up") %>%
  dplyr::select(-c(1, 3), -population, -gdp, -percentage_expenditure) %>%
  drop_na() %>%
  ungroup() %>%
  dplyr::select(-1)
}

x <- transform_1(x)

x_1 <- x %>% filter(year == max(year)) %>% select(-1)
x_predict <- x %>% filter(year != max(year)) %>% slice_sample(n=10) %>% select(-1)

model <- lm(life_expectancy ~ ., data = x_1)
crPlots(model) # regis randu kintamuju tarp kuriu priklausomybe nera tiesine
```



```{r}
transform_2 <- function(x) {
    x %>% 
    mutate(gdp_per_capita = log(gdp_per_capita),
    infant_deaths = log(infant_deaths + 1),
    measles = log(measles + 1),
    total_expenditure = log(total_expenditure + 1),
    under_five_deaths = log(under_five_deaths + 1)
  )
}

x_2 <- transform_2(x_1)
x_predict <- transform_2(x_predict)
write.csv(x_2, "life_modified.csv")

model <- lm(life_expectancy ~ ., data = x_2)
```


### Modelio prielaidos
```{r}
# Liekanu normalumas, homoskadiskumas, liekanu nepriklausomumas, isskirtys
plot(model)
plot(cooks.distance(model))
plot(hatvalues(model))

# Liekanu normalumo testas
shapiro.test(residuals(model))


# homoskadiskumo testas
library(lmtest)
bptest(model)
```


```{r}
crPlots(model)
avPlots(model)
```

```{r}
anova(model) # H0: beta_1 = beta_2 = ... = 0
```


### Modelio parinkimas


```{r}
library(RcmdrMisc)
model_2 <- stepwise(model)
```


### Parametru vertinimas ir interpretacija

```{r}
# Koeficientai
summary(model_2) # kadangi jokie transformuoti kintamieji nepakliuvo -> interpretacija paprasta
library(lm.beta)
# Standartizuoti koeficientai
lm.beta(model_2)

# Pasikliovimo interalai
confint(model_2, )

# Kovarianciu itaka vizualizuota
library(effects)
plot(predictorEffects(model_2))
```


### Multikolinearumas

```{r}
library(psych)

vars <- dplyr::select(x_2, c(adult_mortality, hepatitis_b, total_expenditure,
  hiv_aids, income_composition_of_resources, life_expectancy))
corr.test(vars)


#partial correlation
library(ppcor)
pcor(vars)

# Variance inflation factor
vif(model_2)
```



### Modelio tinkamumo analize
```{r}
summary(model_2) # R-squared = 0.897
# Adj R-squared = 0.892

predictions <- predict(model_2,newdata = x_predict, interval = "prediction")
predictions <- as_tibble(predictions) %>% mutate(n = 1:nrow(predictions))


cols <- c(1,18,19,20,21)

predictions_points <- x_predict %>%
  mutate(pred = predictions) %>% 
  unnest(pred) %>%
  dplyr::select(cols) %>%
  pivot_longer(c(1,2))


ggplot(predictions) + 
  geom_linerange(aes(x=n,ymin=lwr,ymax=upr)) + 
  geom_point(data=predictions_points,aes(x=n,y=value,color=name),size = 4) + 
  scale_x_discrete("Observation") +
  scale_y_continuous("Life Expectancy") + 
  theme_minimal(base_size = 16) + 
  scale_color_brewer("",palette = "Set1")
```
